### ISSUE TITLE
Use Set of Keys rather than list

### ISSUE THREAD

**Issue by FranzSkuffka** [ohanhi/keyboard#11]
I think a `Set Key` is more representative of the problem domain - a key should never occur twice in the pressed list.

I am aware that Set members need to be comparable. What are your thoughts on this?

**Comment by ohanhi** [comment]
You are correct. In some use cases the order of keys matters, though. I initially had the keys in a Set but some people convinced me that eg. Ctrl-S is different from S-Ctrl. This was used at least in the discontinued https://github.com/scottcorgan/keyboard-combo .

**Comment by FranzSkuffka** [comment]
Thank you for elaborating. Would you welcome a PR to add this info to https://github.com/ohanhi/keyboard/blob/master/src/Keyboard.elm#L184

**Comment by ohanhi** [comment]
Sure. Would be great if the tone of voice for the addition also matched the rest of the docs. Thanks!

**Comment by FranzSkuffka** [comment]
senpai, notice my PR :joy:

**Comment by FranzSkuffka** [comment]
We have a thread for the curious to follow and understand this design decision now.
