### ISSUE TITLE
Shift key issues

### ISSUE THREAD

**Issue by atlewee** [ohanhi/keyboard#3]
Hi, first of all thanks for this great package.
Have not had this problem with normal use, but I noticed that if you hold a key pressed down and then press "Shift", the character will be stuck in the list of Keys.
The same thing when holding shift, pressing a key and the releasing shift before releasing the key.

If making a game and using shift as a "down on the ground" button while moving all over with AWSD you could potentially get into some headache    :)
( If you do not have a debugger showing whats in the list of currently pressed keys )

**Comment by ohanhi** [comment]
This is now published in 2.0.0. Here's the upgrade guide: https://github.com/ohanhi/keyboard/blob/master/upgrade-2.x.md
