### ISSUE TITLE
Json decoder

### ISSUE THREAD

**Issue by Skinney** [ohanhi/keyboard#4]
It would be great to have a json decoder that can be passed to `Events.on` so that we can check what key has been pressed when an input is focused.

**Comment by Skinney** [comment]
Yes, I think so. My library contains 400 lines of code, 380 of which is copied out of your project. It would be nice if I could have the same functionality without the code duplication :)

**Comment by ohanhi** [comment]
All right then. Would you want to make a PR?

**Comment by Skinney** [comment]
I could. Not able to get to it before tomorrow though.

**Comment by Skinney** [comment]
Fixed in #7

**Comment by ohanhi** [comment]
Thank you!

**Comment by ohanhi** [comment]
Published in 1.1.0! https://package.elm-lang.org/packages/ohanhi/keyboard/latest/
